version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

  publisher:
    build: ./publisher
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  subscriber:
    build: ./subscriber
    ports:
      - "8001:8001"
    depends_on:
      - kafka
      - mongo
